traefik:
  enabled: true
  namespace: traefik
  repoURL: "https://traefik.github.io/charts"
  chart: traefik
  version: "25.0.0" # Use the latest version or specify the one you prefer
  createNamespace: true

  values:
    # Basic configuration - adjust based on your needs
    ingressClass:
      enabled: true
      isDefaultClass: true

    # Ports configuration
    ports:
      web:
        port: 80
        exposedPort: 80
        expose: true # Changed to true to expose HTTP port
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        expose: true
        protocol: TCP

    # Dashboard
    dashboard:
      enabled: true
      ingressRoute: true
      domain: "traefik.home.lanegoolsby.com"

    # Service configuration
    service:
      type: LoadBalancer # Change to NodePort or ClusterIP if preferred

    # Persistent settings
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data

    # TLS configuration to fix certificate validation error
    ssl:
      insecureSkipVerify: true # Skip certificate validation for backend services

    # Add your custom configuration here
    additionalArguments:
    - "--api.dashboard=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--log.level=INFO"
    - "--serversTransport.insecureSkipVerify=true" # Skip certificate validation
