apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`homeassistant.home.lanegoolsby.com`)
    kind: Rule
    middlewares:
    - name: home-assistant-headers
    services:
    - name: home-assistant
      namespace: home-assistant
      port: 8123
  tls:
    secretName: wildcard-home-lanegoolsby-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: home-assistant-headers
  namespace: home-assistant
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-For: ""
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
