apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`argo.lanegoolsby.com` || `192.168.100.50)
    kind: Rule
    services:
    - name: argo-server
      namespace: argocd
      port: 32400
  tls: {}
