apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`argocd.home.lanegoolsby.com`)
    kind: Rule
    services:
    - name: argocd-server
      namespace: argocd
      port: 443
  tls: {}
---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`traefik.home.lanegoolsby.com`)
    kind: Rule
    services:
    - name: traefik
      namespace: traefik
      port: 443
  tls: {}
