apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: wildcard-home-lanegoolsby-com-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-copier
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-copier
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "create", "update", "patch" ]
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-copier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-copier
subjects:
- kind: ServiceAccount
  name: secret-copier
  namespace: traefik
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wildcard-cert
  namespace: traefik
spec:
  template:
    spec:
      serviceAccountName: secret-copier
      containers:
      - name: secret-copier
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for the certificate to be ready
          kubectl wait --for=condition=Ready certificate/wildcard-home-lanegoolsby-com -n traefik --timeout=300s

          # Copy the secret to each namespace that needs it
          for ns in hello-world home-assistant argocd; do
            kubectl get secret wildcard-home-lanegoolsby-com-tls -n traefik -o yaml | \
            sed "s/namespace: traefik/namespace: $ns/" | \
            kubectl apply -f -
          done
      restartPolicy: OnFailure
  backoffLimit: 3
