apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:lanegoolsby/homelab.git
    targetRevision: init
    path: dns-config
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
