apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
  - chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 35.2.0
    helm:
      valueFiles:
      - $repo/traefik/values.yaml
  - repoURL: https://github.com/lanegoolsby/homelab.git
    targetRevision: init
    ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lanegoolsby/homelab.git
    targetRevision: init
    path: rbac/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
