apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:lanegoolsby/homelab.git
    targetRevision: init
    path: charts/nginx
    helm:
      values: |
        replicaCount: 1
        ingress:
          enabled: true
          hosts:
            - host: nginx.local
              paths:
                - /
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---

