apiVersion: v1
kind: Secret
metadata:
  name: private-repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:lanegoolsby/homelab.git
  sshPrivateKey: |
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBk3gmrw9PyBuY8FAhX9sBbYaF76W2VbXVQRHJ0v+cM6QAAAJj+vL3s/ry9
7AAAAAtzc2gtZWQyNTUxOQAAACBk3gmrw9PyBuY8FAhX9sBbYaF76W2VbXVQRHJ0v+cM6Q
AAAEBvdVL1kWw44YeJ1R0oS8KF3FuUAanif6ELaC0fMuPjnmTeCavD0/IG5jwUCFf2wFth
oXvpbZVtdVBEcnS/5wzpAAAAFGxhbmVAbGFuZWdvb2xzYnkuY29tAQ==
-----END OPENSSH PRIVATE KEY-----
